# Generated by Django 2.2.5 on 2020-05-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('published_date', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('topic_url', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('top_news', models.CharField(max_length=8, null=True)),
                ('domain_tags', models.TextField()),
            ],
        ),
    ]
