# Generated by Django 2.2.5 on 2020-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='sentimental',
            field=models.TextField(null=True),
        ),
    ]
